# Generated by Django 3.2.25 on 2026-05-19 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=500)),
                ('Symptoms', models.CharField(max_length=500)),
                ('additional_precautions', models.CharField(max_length=500)),
                ('prescription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='medical.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height_in_Centimeters', models.CharField(help_text='Height in centimeters', max_length=100)),
                ('Weight_in_kilograms', models.CharField(help_text='Weight in kilograms', max_length=100)),
                ('Allergies', models.TextField(max_length=30)),
                ('Smoker_or_not', models.CharField(max_length=30)),
                ('Chronic_conditions', models.CharField(help_text='Your current long term diseases. <br>Ex. High BP, Diabetes etc', max_length=30)),
                ('patientv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=500)),
                ('phone', models.CharField(help_text='10 digit Mobile Number', max_length=40)),
                ('emergency_contact', models.CharField(max_length=40)),
                ('profession', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(default='patients_profile_pictures/defaultprofilepic.jpg', upload_to='patients_profile_pictures')),
                ('Aadhar_Number', models.IntegerField(help_text='12 digit unique Aadhar Number')),
                ('usertype', models.IntegerField(default=1)),
                ('access_code', models.CharField(default='000000000', max_length=9, unique=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('upload_date', models.DateField(auto_now=True)),
                ('labreportfile', models.FileField(upload_to='lab_reports')),
                ('patientl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
