# Generated by Django 3.2.25 on 2026-05-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_name',
            field=models.CharField(blank=True, help_text='Hospital where the doctor works', max_length=200, null=True),
        ),
    ]
