# Generated by Django 3.2.25 on 2026-05-19 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, unique=True)),
            ],
            options={
                'ordering': ['blood_type'],
            },
        ),
        migrations.CreateModel(
            name='OrganDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('matched', 'Matched'), ('engaged', 'Engaged'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('health_condition', models.TextField(help_text='Current health condition and any relevant medical history')),
                ('age_at_donation', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Additional medical notes', null=True)),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ_donation.bloodtype')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_donations', to='patient.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('engaged', 'Engaged'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('medical_condition', models.TextField(help_text='Current medical condition and why organ is needed')),
                ('age_at_request', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needed_by', models.DateTimeField(blank=True, help_text='Date by which organ is needed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional medical notes', null=True)),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ_donation.bloodtype')),
                ('matched_donation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_matched_with', to='organ_donation.organdonation')),
            ],
            options={
                'ordering': ['-urgency', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('heart', 'Heart'), ('kidney', 'Kidney'), ('liver', 'Liver'), ('lung', 'Lung'), ('pancreas', 'Pancreas'), ('cornea', 'Cornea'), ('bone_marrow', 'Bone Marrow'), ('blood', 'Blood'), ('tissue', 'Tissue'), ('other', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Transaction notes and outcomes', null=True)),
                ('success_rate', models.FloatField(default=0.0, help_text='Estimated or actual success rate')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctorprofile')),
                ('donation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='organ_donation.organdonation')),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donated_transactions', to='patient.patientprofile')),
                ('organ_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ_donation.organtype')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='patient.patientprofile')),
                ('request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='organ_donation.organrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='organrequest',
            name='organ_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ_donation.organtype'),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_requests', to='patient.patientprofile'),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='matched_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_matched_with', to='organ_donation.organrequest'),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='organ_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ_donation.organtype'),
        ),
        migrations.CreateModel(
            name='DoctorApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for approval/rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctorprofile')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_approvals', to='organ_donation.organdonation')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_approvals', to='organ_donation.organrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organtransaction',
            index=models.Index(fields=['status', 'donor'], name='organ_donat_status_c76f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='organtransaction',
            index=models.Index(fields=['status', 'recipient'], name='organ_donat_status_baaa05_idx'),
        ),
        migrations.AddIndex(
            model_name='organrequest',
            index=models.Index(fields=['status', 'organ_type'], name='organ_donat_status_c24a72_idx'),
        ),
        migrations.AddIndex(
            model_name='organrequest',
            index=models.Index(fields=['requester', 'status'], name='organ_donat_request_68f974_idx'),
        ),
        migrations.AddIndex(
            model_name='organrequest',
            index=models.Index(fields=['urgency', 'status'], name='organ_donat_urgency_14b1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='organdonation',
            index=models.Index(fields=['status', 'organ_type'], name='organ_donat_status_efe9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='organdonation',
            index=models.Index(fields=['donor', 'status'], name='organ_donat_donor_i_ca2d0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorapproval',
            unique_together={('donation', 'request', 'doctor')},
        ),
    ]
