# Generated by Django 3.2.25 on 2026-05-19 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('access_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Gender', models.CharField(blank=True, max_length=30)),
                ('Specialisation', models.CharField(max_length=30)),
                ('phone', models.CharField(help_text='10 digit Mobile Number', max_length=40)),
                ('City', models.CharField(max_length=30)),
                ('Registration_Number', models.CharField(max_length=40)),
                ('Registration_Council', models.CharField(max_length=100)),
                ('Registration_year', models.IntegerField()),
                ('Degree', models.CharField(max_length=100)),
                ('College', models.CharField(max_length=100)),
                ('Year_of_completion', models.IntegerField()),
                ('Profile_pic', models.ImageField(default='doctors_profile_pictures/doctor-img2.png', upload_to='doctors_profile_pictures')),
                ('Current_place_of_work', models.CharField(max_length=30)),
                ('Aadhar_Number', models.IntegerField(blank=True, help_text='12 digit unique Aadhar Number')),
                ('usertype', models.IntegerField(default=2)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
